### ISSUE TITLE
Not actually using middleman

### ISSUE THREAD

**Issue by calebeby** [samullman/samullman.github.io#1]
Hey Sam,
I see that your site is laid out for middleman, but it's not actually using it. To do that, you either have to commit/push from the `build` directory on your computer after running `middleman build` or using a CI server to automatically build the files for you. Although I have done this with GitHub/Travis CI/Messy GitHub SSH key so travis can commit, it was not very nice and I recommend moving this repository to GitLab, which has integrated CI and is much easier to use. This is what I'm working on for my personal site. You can find out about GitLab Pages [here](http://pages.gitlab.io/). You can find out about using middleman with this [here](https://gitlab.com/pages/middleman). Basically, you just have to add a `.gitlab-ci.yml` file to the root of your GitLab project.

**Comment by calebeby** [comment]
I say we keep working on it here on GitHub, until it's "ready", and then you can move it to GitLab to add CI.

**Comment by samullman** [comment]
@calebeby thanks for taking a look. I've set up everything like you described. Hitting an error now in Gitlab concerning a failed build via their pipeline.

**Comment by calebeby** [comment]
```ruby
Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for
"rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/dotenv-2.1.1.gem)
```
This makes me think that maybe there is a network error? Can you rerun the build and see if the issue persists?

Separately, an issue with `.gitlab-ci.yml`:
```yml
  - bundle exec middleman build
```
This will build the site to the `build/` directory, but in order to be deployed to GitLab Pages, it needs to be in the `public/` folder. To do this you need:

```yml
  - bundle exec middleman build --build-dir=public
```

**Comment by calebeby** [comment]
If it is not a network error, add `gem install dotenv -v '2.1.1'` above `bundle install`
