### ISSUE TITLE
"Semantic" UI

### ISSUE THREAD

**Issue by calebeby** [samullman/samullman.github.io#2]
Hi again Sam,

I'm concerned about Semantic UI not being ..... semantic. The idea is that your content is the HTML and the CSS is your styles, right? Well, why does Semantic UI have classes like `centered`, `ten`, `wide`, `green`, etc. I think these belong in your CSS, and your HTML should have classes like `app-bar`, `experience-item`, `about-section`.

**Comment by samullman** [comment]
I'm using the [library](http://semantic-ui.com/) for rapid prototyping. I think you make a good case that these styles should be moved to css files, although given that my sites are changing rapidly it might not make sense to do this. Let me know what you think.

**Comment by calebeby** [comment]
Clone [calebeby/samullman.github.io](https://github.com/calebeby/samullman.github.io), and see if you like the css. It really isn't hard to do grid with CSS if you use [Jeet](http://jeet.gs/) or [Neat](http://neat.bourbon.io/). In my fork, I used Jeet.

**Comment by calebeby** [comment]
My fork uses Brunch (powered by node) to compile css, so you have to run `npm install` as well as `bundle install`

**Comment by calebeby** [comment]
Middleman starts brunch automatically via the [external pipeline](https://middlemanapp.com/advanced/external-pipeline/#toc) feature.
